load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "eggc",
    hdrs = glob([
        "include/eggc/*.hpp",
        "include/eggc/impl/*.hpp",
        "include/eggc/detail/*.hpp",
        "include/eggc/impl/*.tpp",
    ]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
